version: '3.3'
services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - "4444"
    volumes:
      - /dev/shm:/dev/shm
  db:
    image: mysql:5.7
    container_name: wordpress_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./docker/test_db_dump.sql:/docker-entrypoint-initdb.d/test_db_dump.sql
    command: mysql -u root -p'123' -e"create database wordpress";
    command: mysql -u root -p'123' wordpress < /docker-entrypoint-initdb.d/test_db_dump.sql
  web:
    build:
      context: ./docker
    container_name: wordpress_web
    depends_on:
      - db
    ports:
      - "80:80"
    links:
      - db:mysql
networks:
  default:
    external:
      name: webproxy
